config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :resturents do
  	resources :reviews, except: [:show, :index]
  end
  get 'pages/about'
  get 'pages/contact'

  root 'resturents#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resturent.rb
class Resturent < ApplicationRecord
	mount_uploader :image, ImageUploader

	has_many :reviews

	validates :name, :address, :phone, :website, :image, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :resturent

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
		only_integer: true,
		greater_than_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "can only a hold number between 1 and 5"
	}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	  before_action :configure_permitted_parameters, if: :devise_controller?

	  protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
	    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
	    
	  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/resturents_controller.rb
class ResturentsController < ApplicationController
  before_action :set_resturent, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show] 

  # GET /resturents
  # GET /resturents.json
  def index
    @resturents = Resturent.all
  end

  # GET /resturents/1
  # GET /resturents/1.json
  def show
    @reviews = Review.where(resturent_id: @resturent.id)
  end

  # GET /resturents/new
  def new
    @resturent = Resturent.new
  end

  # GET /resturents/1/edit
  def edit
  end

  # POST /resturents
  # POST /resturents.json
  def create
    @resturent = Resturent.new(resturent_params)

    respond_to do |format|
      if @resturent.save
        format.html { redirect_to @resturent, notice: 'Resturent was successfully created.' }
        format.json { render :show, status: :created, location: @resturent }
      else
        format.html { render :new }
        format.json { render json: @resturent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturents/1
  # PATCH/PUT /resturents/1.json
  def update
    respond_to do |format|
      if @resturent.update(resturent_params)
        format.html { redirect_to @resturent, notice: 'Resturent was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturent }
      else
        format.html { render :edit }
        format.json { render json: @resturent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturents/1
  # DELETE /resturents/1.json
  def destroy
    @resturent.destroy
    respond_to do |format|
      format.html { redirect_to resturents_url, notice: 'Resturent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturent
      @resturent = Resturent.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, Only admin can do that!" 
      end
    end

    # Only allow a list of trusted parameters through.
    def resturent_params
      params.require(:resturent).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_resturent
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

 

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.resturent_id = @resturent.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to resturent_path(@resturent), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to resturent_path(@resturent), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_resturent
      @resturent = Resturent.find(params[:resturent_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else."
     
        
      end
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_message!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg ) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
			resource: resource.class.model_name.human.downcase)

		html = <<-HTML
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
				<span class="sr-only">Close</span>
			</button>
			<h4>#{sentence}</h4>
			#{messages}
		</div>
		HTML

		html.html_safe
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resturents_helper.rb
module ResturentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpDemo</title>
    <%= render 'shared/bootstrap' %>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container-fluid">

      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable"> 
            <button type="button" class="close" data-dismiss="alert"> <span aria-hidden="true">&time;</span><span class="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}"%>
          </div>
        <% end -%>
      <% end -%>

      
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
  
</html>

app/views/pages/about.html.erb
<h1>Welcome to YelpDemo!</h1>

<p>Lorem ipsum dolor sit amet consectetur<%= link_to "BaseRails", "http://www.baserails.com"  %> <a href="http://www.baserails.com" target="_blank">adipisicing </a> elit. Repellendus, ea dolorum laborum doloribus obcaecati nesciunt doloremque in vel labore, necessitatibus magnam provident suscipit alias, illo eaque dolor non eius reiciendis cumque porro? Unde impedit blanditiis, accusantium nostrum dolor pariatur assumenda ad quo. Natus hic explicabo ipsum tempora accusamus eum in quam, voluptatem corrupti eius soluta, incidunt ducimus sequi, cum praesentium ex quis nam veritatis! Debitis, impedit soluta minima praesentium maiores, explicabo mollitia. Quas cum nisi ratione, dolor odio reprehenderit fugiat cupiditate, tempora minus voluptate praesentium rerum porro officia doloremque eos commodi, totam enim. Repellendus similique fugiat, dolores, repellat optio ut.</p>

app/views/pages/contact.html.erb
<h1>We would like to hear for you!</h1>
<p>Contact at as mohiuddinoshim@yahoo.com</p>
<p>0181-2027999</p>

app/views/resturents/_form.html.erb
<%= form_with(model: resturent, :html => {multipart: true}) do |form| %>
  <% if resturent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resturent.errors.count, "error") %> prohibited this resturent from being saved:</h2>

      <ul>
      <% resturent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :website %>
    <%= form.text_field :website, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resturents/edit.html.erb
<h1>Editing Resturent</h1>

<%= render 'form', resturent: @resturent %>

<%= link_to 'Show', @resturent, class: "btn btn-link" %> |
<%= link_to 'Back', resturents_path, class: "btn btn-link" %>

app/views/resturents/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h2>Yelpdemo is the best platform to find reviews for local resturent</h2>
  <h3>Explore the fovorite diners, pastry shops, and entieries in your comunity. <br>
  Leave revious and ratings for your fellow foodies.</h3>
</div>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end -%>
    </tr>
  </thead>

  <tbody>
    <% @resturents.each do |resturent| %>
      <tr>
        <td><%= link_to resturent.name, resturent %></td>
        <td><%= resturent.address %></td>
        <td><%= resturent.phone %></td>
        <td><%= link_to resturent.website, resturent.website %></td>
        
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Show', resturent, class: "btn btn-link" %></td>
          <td><%= link_to 'Edit', edit_resturent_path(resturent), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', resturent, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end -%>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Resturent', new_resturent_path, class: "btn btn-link" %>

<% end -%>

app/views/resturents/new.html.erb
<h1>New Resturent</h1>

<%= render 'form', resturent: @resturent %>

<%= link_to 'Back', resturents_path, class: "btn btn-link" %>

app/views/resturents/show.html.erb
<div class="row">
	<div class="col-md-3">
		<%= image_tag @resturent.image_url %>
			<h2>
			  <%= @resturent.name %>
			</h2>

			<p>
			  <strong>Address:</strong>
			  <%= @resturent.address %>
			</p>

			<p>
			  <strong>Phone:</strong>
			  <%= @resturent.phone %>
			</p>

			<p>
			  <strong>Website:</strong>
			  <%= link_to @resturent.website, @resturent.website  %>
			</p>


			<%= link_to "Create Review",  new_resturent_review_path(@resturent), class: "btn btn-primary" %>

		  <iframe
		  width="230"
		  height="230"
		  frameborder="0" style="border:0"
		  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCnkbdrB_sVMitSObA8Vol7zfs3I8dYNsM
		    &q=<%= @resturent.address.parameterize %>" allowfullscreen>
		</iframe>

	</div>

	<div class="col-md-9">
			<% if @reviews.blank? %>
				<h3>No reviews yet. Be the first to write one!</h3>
			<% else %>
				<% @reviews.each do |review|%>

				<div class="col-md-3">
					<%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]},"%>
					<p><%= review.created_at.strftime("%-m/%-d/%y") %></p>
				</div>

			<div class="col-md-9">
					<div class="star-rating" data-score= <%= review.rating %>></div>
					<p><%= review.comment %></p>

					<% if user_signed_in? %>
						<% if (review.user == current_user) || (current_user.admin?) %>
							<%= link_to "Edit", edit_resturent_review_path(@resturent, review) %>
							<%= link_to "Delete", resturent_review_path(@resturent, review), method: :delete %>
							<% end -%>
					<% end -%>
			</div>
				
			<% end -%>
		<% end -%>
	</div>
</div>



<%= link_to 'Edit', edit_resturent_path(@resturent), class: "btn btn-link" %> |
<%= link_to 'Back', resturents_path, class: "btn btn-link" %>

<script>
$('.star-rating').raty({
	path: '/assets',
	readOnly: true,
	score: 1

});
</script>

app/views/reviews/_form.html.erb
<%= form_with(model: [@resturent, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">

      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>

      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', resturent_path(@resturent) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', resturent_path(@resturent) %>

app/views/shared/_bootstrap.html.erb
  <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript with Jquery -->
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="crossorigin="anonymous"></script>

     <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

app/views/shared/_footer.html.erb
    <p>copyright @mahichowdhury</p>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "YelpDemo", root_path, class: "navbar-brand"  %>
    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Pages", pages_about_path%></li>
        <li> <%= link_to "Contact", pages_contact_path%></li>
      
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in?%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% else %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% end -%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>